AWSTemplateFormatVersion: 2010-09-09

Resources: 

# Vpc,create
  Vpc10:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/20
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: Vpc10cf

# InternetGateWay,create
  InternetGateWay10:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: InternetGateWay10cf

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc10
      InternetGatewayId: !Ref InternetGateWay10

# Subnet,create
  PublicSubnet11:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      VpcId: !Ref Vpc10
      CidrBlock: 10.10.0.0/23
      Tags:
        - Key: Name
          Value: PublicSubnet11cf

  PrivateSubnet11:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      VpcId: !Ref Vpc10
      CidrBlock: 10.10.2.0/23
      Tags:
        - Key: Name
          Value: PrivateSubnet11cf

  PublicSubnet12:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      VpcId: !Ref Vpc10
      CidrBlock: 10.10.4.0/23
      Tags:
        - Key: Name
          Value: PublicSubnet12cf

  PrivateSubnet12:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      VpcId: !Ref Vpc10
      CidrBlock: 10.10.6.0/23
      Tags:
        - Key: Name
          Value: PrivateSubnet12cf

# RouteTable,RouteTableAssociation,Route,create
  RouteTable10pus11:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc10
      Tags:
        - Key: Name
          Value: RouteTable10pus11cf
  
  RouteTableAssociation10pus11:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet11
      RouteTableId: !Ref RouteTable10pus11

  Route10pus11:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable10pus11
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateWay10

  RouteTable10prs11:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc10
      Tags:
        - Key: Name
          Value: RouteTable10prs11cf

  RouteTableAssociation10prs11:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet11
      RouteTableId: !Ref RouteTable10prs11

  RouteTable10pus12:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc10
      Tags:
        - Key: Name
          Value: RouteTable10pus12cf

  RouteTableAssociation10pus12:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet12
      RouteTableId: !Ref RouteTable10pus12

  Route10pus12:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable10pus12
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateWay10

  RouteTable10prs12:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc10
      Tags:
        - Key: Name
          Value: RouteTable10prs12cf

  RouteTableAssociation10prs12:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet12
      RouteTableId: !Ref RouteTable10prs12

# Ec2SecurityGroup,create
  SecurityGroup10pus11:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Sg10pus11
      GroupDescription: Sgd10pus11
      VpcId: !Ref Vpc10
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref SecurityGroup10elb10
      Tags:
        - Key: Name
          Value: SecurityGroup10pus11cf

# RdsSecurityGroup,create
  SecurityGroup10prs11:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Sg10prs11
      GroupDescription: Sgd10prs11
      VpcId: !Ref Vpc10
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref SecurityGroup10pus11
      Tags:
        - Key: Name
          Value: SecurityGroup10prs11cf

# ElbSecurityGroup,create
  SecurityGroup10elb10:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Sg10elb10
      GroupDescription: Sgd10elb10
      VpcId: !Ref Vpc10
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SecurityGroup10elb10cf

# Ec2,create
  Ec210:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: raisetech-aws-kei-key 
      IamInstanceProfile: !Ref S3IamInstanceProfile10
      ImageId: ami-035d55281a86f9439
      InstanceType: t2.micro
      Monitoring: false
      NetworkInterfaces: 
      - AssociatePublicIpAddress: true
        DeviceIndex: 0
        GroupSet: 
          - !Ref SecurityGroup10pus11
        SubnetId: 
          !Ref PublicSubnet11
      Tags:
        - Key: Name
          Value: Ec210cf

# RdsSubnetGroup,create          
  RdsdbSubnetGroup10:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Rdsdbsg10 
      SubnetIds:
        - !Ref PrivateSubnet11
        - !Ref PrivateSubnet12

# RDS,create
  Rds10:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      AvailabilityZone: "ap-northeast-1a"
      BackupRetentionPeriod: 0
      DBInstanceIdentifier: rds10aws
      DBName: rds10awscf
      DBSubnetGroupName: !Ref RdsdbSubnetGroup10
      Engine: mysql
      EngineVersion: "8.0.33"
      MasterUsername: rds10admin
      MasterUserPassword: rds10admincf
      MultiAZ: false
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref SecurityGroup10prs11
      Tags:
        - Key: Name
          Value: Rds10cf

# Elb,create
  Elb10:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: elb10alb
      Scheme: internet-facing
      SecurityGroups: 
        - !Ref SecurityGroup10elb10
      Subnets: 
        - !Ref PublicSubnet11
        - !Ref PublicSubnet12
      Tags: 
        - Key: Name
          Value: Elb10cf
      Type: application

# TargetGroup,create
  Tg10:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      IpAddressType: ipv4
      Matcher: 
        HttpCode: "200"
      Name: tg10alb
      Port: 80
      Protocol: HTTP
      ProtocolVersion: HTTP1
      Tags: 
        - Key: Name
          Value: Tg10cf
      Targets: 
        - Id: !Ref Ec210
      TargetType: instance
      UnhealthyThresholdCount: 2
      VpcId: !Ref Vpc10

# Listener,create
  Listener10:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref Tg10
      LoadBalancerArn: !Ref Elb10
      Port: 80
      Protocol: HTTP

# S3,create
  S3Bucket10:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: s3bucket10-cf
      Tags:
        - Key: Name
          Value: S3Bucket10cf

# IamRole,create
  S3IamRole10:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"

# IamPolicy,create
  S3IamPolicy10:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: s3access10
      Roles:
       - !Ref S3IamRole10
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - "s3:ListAllMyBuckets"
            - "s3:GetBucketLocation"
          Resource: "arn:aws:s3:::*"
        - Effect: Allow
          Action: "*"
          Resource:
            - "arn:aws:s3:::s3bucket10-cf"
            - "arn:aws:s3:::s3bucket10-cf/*"

# IamInstanceProfile,create
  S3IamInstanceProfile10:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref S3IamRole10
