---
- hosts: 43.206.222.229
  become: true
  tasks:

  - name: upgrade all packages
    ansible.builtin.yum:
      name: '*'
      state: latest

  - name: install git to target node
    ansible.builtin.yum:
      name: 
        - gcc-c++
        - make
        - patch
        - git
        - curl
        - zlib-devel
        - openssl-devel
        - ImageMagick-devel
        - readline-devel
        - libcurl-devel
        - libffi-devel
        - libicu-devel
        - libxml2-devel
        - libxslt-devel
      state: present

  - name: nodejs17.x check
    ansible.builtin.stat:
      path: /etc/yum.repos.d/nodesource-el7.repo
    register: nodesource_repo

  - name: setup nodejs17.x
    shell: "curl -fsSL https://rpm.nodesource.com/setup_14.x | bash -"
    when: not nodesource_repo.stat.exists
    changed_when: false

  - name: install node.js to taget node
    ansible.builtin.yum:
      name: nodejs
      state: latest

  - name: install mysql to taget node
    ansible.builtin.yum:
      name: mysql
      state: present
