---
- hosts: webserver
  become: true
  tasks:

  - name: Upgrade all packages
    ansible.builtin.yum:
      name: '*'
      state: latest

  - name: Install git to target node
    ansible.builtin.yum:
      name: 
        - gcc-c++
        - make
        - patch
        - git
        - curl
        - zlib-devel
        - openssl-devel
        - ImageMagick-devel
        - readline-devel
        - libcurl-devel
        - libffi-devel
        - libicu-devel
        - libxml2-devel
        - libxslt-devel
      state: present

  - name: Nodejs17.x check
    ansible.builtin.stat:
      path: /etc/yum.repos.d/nodesource-el7.repo
    register: nodesource_repo

  - name: Setup nodejs17.x
    shell: curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash - #"curl -fsSL https://rpm.nodesource.com/setup_14.x | bash -"
    when: not nodesource_repo.stat.exists
    changed_when: false

  - name: Install node.js to taget node
    ansible.builtin.yum:
      name: nodejs-v17.9.1
      state: present

  - name: Install mysql to taget node
    ansible.builtin.yum:
      name: mysql
      state: present
